// Docker first-boot initialisation script.
//
// Called by docker-entrypoint.sh ONLY when ~/.cline/kanban/remote.db does
// not yet exist (first container start). On subsequent starts this file is
// never executed.
//
// What it does:
//   1. Reads admin credentials and auth settings from env vars.
//   2. Writes remote-config.json with auth settings.
//   3. Creates remote.db (signing secret, VAPID keys, tables).
//   4. Creates the admin user account (local user + admin role in remote.db).
//   5. Prints credentials to stdout (important for auto-generated passwords).
//
// Compiled into dist/docker-init.js by the existing build.mjs step.
// No separate build required.

import { randomBytes } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

import { loadRemoteConfig, saveRemoteConfig } from "./remote/config-store";
import { createRemoteAuth } from "./server/remote-auth";

// ── Helpers ────────────────────────────────────────────────────────────────

function readEnv(key: string, fallback = ""): string {
	return (process.env[key] ?? fallback).trim();
}

function parseList(value: string): string[] {
	return value
		.split(",")
		.map((s) => s.trim())
		.filter(Boolean);
}

function generatePassword(): string {
	const adjectives = [
		"amber",
		"brave",
		"calm",
		"dark",
		"eager",
		"fair",
		"gold",
		"jade",
		"kind",
		"lush",
		"mute",
		"nova",
		"opal",
		"pine",
		"quiet",
		"rose",
		"sage",
		"teal",
		"umber",
		"vivid",
	];
	const nouns = [
		"atlas",
		"birch",
		"cedar",
		"delta",
		"echo",
		"frost",
		"grove",
		"haze",
		"inlet",
		"jetty",
		"knoll",
		"ledge",
		"marsh",
		"nexus",
		"orbit",
		"prism",
		"quill",
		"ridge",
		"stone",
		"tower",
	];
	const buf = randomBytes(4);
	const adj = adjectives[buf[0]! % adjectives.length]!;
	const noun = nouns[buf[1]! % nouns.length]!;
	const digits = ((buf[2]! << 8) | buf[3]!).toString().slice(-4).padStart(4, "0");
	return `${adj}-${noun}-${digits}`;
}

function box(lines: string[]): string {
	const width = Math.max(...lines.map((l) => l.length)) + 4;
	const border = "═".repeat(width - 2);
	const pad = (s: string) => `║  ${s.padEnd(width - 4)}  ║`;
	return [`╔${border}╗`, ...lines.map(pad), `╚${border}╝`].join("\n");
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
	const dataDir = join(homedir(), ".cline", "kanban");
	await mkdir(dataDir, { recursive: true });

	// ── Read env vars ──────────────────────────────────────────────────────

	const adminEmail = readEnv("KANBAN_ADMIN_EMAIL", "admin@localhost");
	let adminPassword = readEnv("KANBAN_ADMIN_PASSWORD");
	const passwordWasAutoGenerated = !adminPassword;
	if (passwordWasAutoGenerated) {
		adminPassword = generatePassword();
	}

	const rawAuthMode = readEnv("KANBAN_AUTH_MODE", "both");
	const authMode: "workos" | "password" | "both" =
		rawAuthMode === "workos" || rawAuthMode === "password" ? rawAuthMode : "both";

	const allowedEmails = parseList(readEnv("KANBAN_ALLOWED_EMAILS"));
	const allowedEmailDomains = parseList(readEnv("KANBAN_ALLOWED_DOMAINS"));
	const publicBaseUrl = readEnv("KANBAN_PUBLIC_URL");

	// ── Step 1: write remote-config.json ──────────────────────────────────
	// Start with defaults then override. localUsers populated after hashing.

	const config = await loadRemoteConfig();
	await saveRemoteConfig({
		...config,
		authMode,
		allowedEmails,
		allowedEmailDomains,
		publicBaseUrl,
		localUsers: [], // will be updated after hashing the password
		password: "", // shared password disabled — admin uses per-user account
	});

	// ── Step 2: create remote.db + hash password ───────────────────────────

	const remoteAuth = await createRemoteAuth();

	const passwordHash = await remoteAuth.hashPassword(adminPassword);

	// ── Step 3: write admin user into remote-config.json ──────────────────

	const updatedConfig = await loadRemoteConfig();
	await saveRemoteConfig({
		...updatedConfig,
		localUsers: [
			{
				email: adminEmail,
				passwordHash,
				createdAt: Date.now(),
			},
		],
	});

	// ── Step 4: create the remote_users row and promote to admin ──────────
	// getOrCreateUserRecord creates the row with role="viewer" by default.
	// setUserRole then promotes to admin.

	const userRecord = remoteAuth.getOrCreateUserRecord(adminEmail, "Admin");
	remoteAuth.setUserRole(userRecord.uuid, "admin");

	remoteAuth.close();

	// ── Step 5: print credentials ──────────────────────────────────────────

	// biome-ignore lint/suspicious/noConsole: intentional startup output
	console.log("\n[kanban] First-boot initialisation complete.\n");

	const credLines = [
		"KANBAN ADMIN CREDENTIALS",
		"",
		`Email:    ${adminEmail}`,
		`Password: ${passwordWasAutoGenerated ? adminPassword : "(set via KANBAN_ADMIN_PASSWORD)"}`,
		"",
		`Auth mode:  ${authMode}`,
		`Data dir:   ${dataDir}`,
	];

	if (publicBaseUrl) {
		credLines.push(`Public URL: ${publicBaseUrl}`);
	}

	if (passwordWasAutoGenerated) {
		credLines.push("", "SAVE YOUR PASSWORD — it will not be shown again.");
	}

	// biome-ignore lint/suspicious/noConsole: intentional startup output
	console.log(box(credLines));
	// biome-ignore lint/suspicious/noConsole: intentional startup output
	console.log("");
}

main().catch((err) => {
	// biome-ignore lint/suspicious/noConsole: error output
	console.error("[kanban] docker-init failed:", err);
	process.exit(1);
});
